### ISSUE TITLE
Collection search doesn't work

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav-plugin-simplesearch#118]
Hi ! I tried to follow the instructions carefully, but couldn't make simplsearch work on page searches (global search works well).

Here's my code :

```
---
title: Blog
content:
    items: @self.children
    limit: 10
    order:
        by: date
        dir: desc
    pagination: true
    url_taxonomy_filters: true
simplesearch:
    route: @self
    filters:
        - @self
    filter_combinator: and
---
...
```

When submitting the form, the query is correctly appended to the url, but the listing page shows all the items, just as if no query was set.
Is it a bug ?
