### ISSUE TITLE
somplesearch search results

### ISSUE THREAD

**Issue by calvez** [getgrav/grav-plugin-simplesearch#138]
Hello!

I'm just not able to make it work. 
Grav and simple search are the latest version, the simplesearch.yaml is here:

```
enabled: true
built_in_css: true
display_button: false
min_query_length: 3
route: /search
search_content: rendered
template: simplesearch_results
filters:
  category:
    - none@
filter_combinator: and
ignore_accented_characters: false
order:
  by: date
  dir: desc

```
you can check the site here:
[](https://tozsdeabc.bet.hu)

search queries looks this way:
[](https://tozsdeabc.bet.hu/?query=index)

And if you include the /search as the config suggest it's ok:
[](https://tozsdeabc.bet.hu/search?query=index)

I already tried evey suggestion. The js is loaded, the index is ok, the results are perfect....

Searchbox looks like this:
```
                <div class="searchbox">
                    <label for="search-by"><i class="fa fa-search"></i></label>
                        {% include 'partials/simplesearch_searchbox.html.twig' %}
                    <span data-search-clear><i class="fa fa-close"></i></span>
                </div>
```
The searchbox twig is basically the same as original:
```
        <input
            name="query"
            class="search-input"
            type="text"
            {% if min_chars > 0 %} min="{{- min_chars -}}" {% endif %}
            required
            placeholder="{{"PLUGIN_SIMPLESEARCH.SEARCH_PLACEHOLDER"|t}}"
            value="{{ query }}"
            data-search-invalid="{{ "PLUGIN_SIMPLESEARCH.SEARCH_FIELD_MINIMUM_CHARACTERS"|t(min_chars)|raw }}"
            data-search-separator="{{ config.system.param_sep }}"
            data-search-input="{{ base_url }}{{ config.plugins.simplesearch.route == '@self' ? '' : (config.plugins.simplesearch.route == '/' ? '' : config.plugins.simplesearch.route) }}"
        />
```
