### ISSUE TITLE
Many page are out of scope even with category set to @none / none@ / null

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-simplesearch#143]
Hi there!

A lot of pages seems to be out of the scope of simple search.
It happen to pages with or without a category meta so i don't get it.

I've follow advices from other issues to search site wide by trying `@none`,`none@`, `null` without success.

Here is my configuration:

```yaml
enabled: true
built_in_css: false
built_in_js: true
display_button: true
min_query_length: 3
route: /search
search_content: rendered
template: search_results
filters:
  category:
    - '@none'
filter_combinator: or
ignore_accented_characters: true
order:
  by: title
  dir: asc
```

For exemple, I've a videos pages full of project, one of them is called 'Hipanema' and when searching for the string `Hipanema` it return no result...

<img width="867" alt="screen shot 2018-01-21 at 08 30 27" src="https://user-images.githubusercontent.com/10623367/35191849-a6790158-fe85-11e7-923c-e6a9b1123a61.png">

Here is the `project.md` file:

```
---
title: projects
taxonomy:
    category:
        - videos
videos:
    -
        title: rio
        image: rio.jpg
        youtube: 9HIOlljzJof
    -
        title: hipanema
        image: hipanema.jpg
        youtube: ORjji34jie2
```

I've also tried without taxonomy and the result is the same...

I hope those informations are useful, let me know if you need more.

Thank you so much for your help
