### ISSUE TITLE
How to configure redirection on submit?

### ISSUE THREAD

**Issue by stat92** [getgrav/grav-plugin-simplesearch#167]
simplesearch.yaml file:
```
enabled: true
built_in_css: true
built_in_js: true
display_button: false
min_query_length: 3
route: /help
search_content: raw
template: categories
filters: @self
filter_combinator: or
ignore_accented_characters: false
order:
    by: date
    dir: desc
```

I have `header.twig.html` template which have `simplesearch-box` element. This template is added to different routes. So for `simplesearch` to work I need to redirect it to `/help` page because of `route: /help` configured. How can I do that or may be there are another ways to get same behavior?

Thanks in advance
