### ISSUE TITLE
No results are produced

### ISSUE THREAD

**Issue by asimakos** [getgrav/grav-plugin-simplesearch#183]
I have integrated the search bar with glass button into my custom theme and applied the following config to /user/config/plugins/simplesearch.yaml:

```
enabled: true
built_in_css: true
built_in_js: true
display_button: true
min_query_length: 3
route: /search
search_content: rendered
template: simplesearch_results
filters:
  category:
    - '@none'
filter_combinator: and
ignore_accented_characters: false
order:
  by: date
  dir: desc

```
Unfortunately when i search for a keyword it routes to http://myserver/?searchfield=energy **results page is not routed properly and additionally it gives no results**. I have also added simplesearch_results.html.twig into templates folder and simplesearch_searchbox.html.twig into templates/partials folder. Additionally i have not created any category or taxonomy at all in my blog! Any idea what i am missing?

Regards
