### ISSUE TITLE
Define @self as simplesearch route

### ISSUE THREAD

**Issue by bpaugam** [getgrav/grav-plugin-simplesearch#32]
I would like to set up a self-controlled search page where the search route is the route of the page itself. I want to do that:

```
my_page_frontmatter
---
simplesearch:
    route: '@self'
    filters: '@self'
    filter_combinator: and
content:
    items: '@self.descendants'
```

Problem is, it seems I can only define absolute routes overrides.
