### ISSUE TITLE
Self-controlled search page doesn't actually search

### ISSUE THREAD

**Issue by hunternet93** [getgrav/grav-plugin-simplesearch#51]
I'm trying to set up a per-page search feature as described [here](https://github.com/getgrav/grav-plugin-simplesearch#2-self-controlled-search-page), however when searching the template simply renders the same page, instead of filtering content by the search query.

Steps to reproduce:

1. Download and extract the [blog site skeleton](https://github.com/getgrav/grav-skeleton-blog-site/releases/download/1.1.1/grav-skeleton-blog-site-v1.1.1.zip). I'm using PHP's built-in webserver for testing, but I've also tried Apache with identical results.

2. Edit the file `user/pages/01.blog/blog.md` and append the following to its frontmatter:
    ```yaml
simplesearch:
    route: /blog
    filters:
        - /blog
        - @taxonomy: [tag]
    filter_combinator: and
    ```

3. Open the site in a browser and attempt searching. Searching will redirect the page to [/blog/query:<query string>](#) as expected, but then will load exactly the same page again, without filtering by the search query.

Did I miss a step when setting up simplesearch?
