### ISSUE TITLE
Search fail if key `filters:` is not present

### ISSUE THREAD

**Issue by magnetik** [getgrav/grav-plugin-simplesearch#70]
Hi,

When using the admin plugin, when I remove the only tag in the `Category filter`, the line `filters:` is deleted from `simplesearch.yaml`.

When this line is not present, the search fail even when there are result.

After adding the line `filters:` manually, the search works again.  

And when editing another field in the admin plugin, the line is removed again.

**Comment by flaviocopes** [comment]
I don't see any problem. Are you using the latest releases of Grav + Admin + SimpleSearch?

**Comment by gitname** [comment]
I see this also.

Here are my observations from 3 experiments I did while using Grav v1.1.5, Admin v1.2.2, and SimpleSearch v1.9.2.

I ran experiment *C* because I didn't know whether the only reason the search yielded 0 results in experiment *B* was that I was defining a `filter_combinator` without defining a `filter`.

## A. With the `filters` key present

*simplesearch.yaml*:

```yaml
enabled: true
built_in_css: true
display_button: true
min_query_length: 3
route: /search
template: simplesearch_results
filters:
filter_combinator: and
order:
    by: date
    dir: desc
```

The search yields **1** result.

Here's a screenshot of search results page in my web browser:

![image](https://cloud.githubusercontent.com/assets/7143133/18660155/cfccf4a8-7ec3-11e6-9114-12a74f5bef63.png)

---

## B. With the `filters` key absent

*simplesearch.yaml*:

```yaml
enabled: true
built_in_css: true
display_button: true
min_query_length: 3
route: /search
template: simplesearch_results
filter_combinator: and
order:
    by: date
    dir: desc
```

The search yields **0** result.

Here's a screenshot of search results page in my web browser:

![image](https://cloud.githubusercontent.com/assets/7143133/18660165/e4eae188-7ec3-11e6-9ab3-d02225aff418.png)

---

## C. With the `filters` and `filter_combinator` key absent

```yaml
enabled: true
built_in_css: true
display_button: true
min_query_length: 3
route: /search
template: simplesearch_results
order:
    by: date
    dir: desc
```

The search yields **0** results.

Here's a screenshot of search results page in my web browser:

![image](https://cloud.githubusercontent.com/assets/7143133/18660312/99acd8b0-7ec4-11e6-924a-e6b32f89d6b9.png)

---

For reference, I'm using PHP 5.5.9.
