### ISSUE TITLE
[closed] No results

### ISSUE THREAD

**Issue by muuvmuuv** [getgrav/grav-plugin-simplesearch#76]
I've installed the latest GRAV + Admin + simplesearch and added the form in my blog sidebar. The blog ist routed under /blog and is not the home directory, so the search submit was routing to it every time and no result page was shown. After I changed the {{ base_url }} to {{ base_url_absolute }} in the search box template, the result page is shown, but without any results. I tried to let everything default, but it did not work.

site where the error can we shown: http://dev.influxe-gaming.de/blog

simplesearch.conf:

```
enabled: true
built_in_css: false
display_button: false
min_query_length: 2
route: /suche
template: results.search
filters:
  category:
    - blog
filter_combinator: and
order:
  by: date
  dir: desc
```

sidebar include:

```
    {% if config.plugins.simplesearch.enabled and page.header.sidebar.simplesearch.enabled %}
      <widget class="search" style="order:{{ page.header.sidebar.simplesearch.order }}">
        {% include 'partials/box.search.html.twig' %}
      </widget>
    {% endif %}
```

box.search.html.twig: http://hastebin.com/uvuketufuw.bash
results.search.html.twig: http://hastebin.com/bilopegone.scala
